part: RS1G126
datasheet:
  lang: en
  source: local-reference
  file: C:\Users\OoiJianHong\Downloads\Reference\Reference\RS1G126_(RevA.4).pdf
  extract: C:\Users\OoiJianHong\Eugene's Repo\PythonAutomation\ate\config\datasheets\text\rs1g126.txt
specs:
- id: ICC_uA
  unit: uA
  max: 1.0
  test: icc
  source: local:RS1G126_(RevA.4).pdf
- id: DELTA_ICC_uA
  unit: uA
  max: 500.0
  test: delta_icc
  source: local:RS1G126_(RevA.4).pdf dICC 3V to 5.5V
- id: II_uA
  unit: uA
  max: 1.0
  test: ii
  source: local:RS1G126_(RevA.4).pdf II +25C
- id: IOZ_uA
  unit: uA
  max: 10.0
  test: ioz
  source: local:RS1G126_(RevA.4).pdf IOZ VCC=3.6V
- id: VCC_V
  unit: V
  min: 1.65
  max: 5.5
  source: local:RS1G126_(RevA.4).pdf
